In [7]:
import pandas as pd
import os
from pathlib import Path

os.chdir(r"C:\Users\JackP\Downloads\BennettHypothesisValidation")
annual_max_long = pd.read_csv(r"./data/Loan Data/annual_max_long.csv")
average_loan_amounts_clean = pd.read_csv(r"./data/Loan Data/average_loan_amounts_clean.csv")

In [12]:
sub_cap_df

    year          level   dependency      class  amount
0   1995  Undergraduate    Dependent   Freshman    2625
1   1995  Undergraduate    Dependent  Sophomore    2625
2   1995  Undergraduate    Dependent    Junior+    4000
3   1995  Undergraduate  Independent   Freshman    2625
4   1995  Undergraduate  Independent  Sophomore    2625
5   1995  Undergraduate  Independent    Junior+    4000
6   1995       Graduate  Independent        Any    8500
7   2007  Undergraduate    Dependent   Freshman    3500
8   2007  Undergraduate    Dependent  Sophomore    4500
9   2007  Undergraduate    Dependent    Junior+    5500
10  2007  Undergraduate  Independent   Freshman    3500
11  2007  Undergraduate  Independent  Sophomore    4500
12  2007  Undergraduate  Independent    Junior+    5500
13  2007       Graduate  Independent        Any    8500
14  2008  Undergraduate    Dependent   Freshman    3500
15  2008  Undergraduate    Dependent  Sophomore    4500
16  2008  Undergraduate    Dependent    Junior+    5500
17  2008  Undergraduate  Independent   Freshman    3500
18  2008  Undergraduate  Independent  Sophomore    4500
19  2008  Undergraduate  Independent    Junior+    5500
20  2008       Graduate  Independent        Any       0